<?php require_once __DIR__ . "/../inc/header.php"; ?>

<div class="row">

<div class="col">

	<h3 class="text-center display-4">Predefined Variables</h3>
    <hr>


    <?php 
echo '<pre>';
print date("m/d/y G.i:s<br>", time());

?>

    <p>PHP provides a large number of predefined variables to any script which it runs. PHP provides an additional set of predefined arrays containing variables from the web server the environment, and user input. These new arrays are called <code>superglobals</code> −</p>
    <p>All the following variables are automatically available in every scope.</p>

    <hr>
    <h3>PHP Superglobals</h3>
    <ul>
        <li><strong>$GLOBALS</strong>- Contains a reference to every variable which is currently available within the global scope of the script. The keys of this array are the names of the global variables.</li>
        <li><strong>$_SERVER </strong>This is an array containing information such as headers, paths, and script locations. The entries in this array are created by the web server. There is no guarantee that every web server will provide any of these.</li>
        <li><strong>$_GET</strong> An associative array of variables passed to the current script via the HTTP GET method.</li>
        <li><strong>$_POST</strong> An associative array of variables passed to the current script via the HTTP POST method.</li>
        <li><strong>$_FILES</strong> An associative array of items uploaded to the current script via the HTTP POST method.</li>
        <li><strong>$_REQUEST</strong> An associative array consisting of the contents of $_GET, $_POST, and $_COOKIE.</li>
        <li><strong>$_COOKIE </strong>An associative array of variables passed to the current script via HTTP cookies.</li>
        <li><strong>$_SESSION </strong>An associative array containing session variables available to the current script.</li>
        <li><strong>$_PHP_SELF </strong>A string containing PHP script file name in which it is called.</li>
        <li><strong>$php_errormsg </strong> $php_errormsg is a variable containing the text of the last error message generated by PHP.</li>        
    </ul>

    <hr>
    <h3>Server variables: $_SERVER</h3>
    <ul>
    <li>$_SERVER['PHP_SELF']</li>
    <li>$_SERVER['argv']</li>
    <li>$_SERVER['argc']</li>
    <li>$_SERVER['GATEWAY_INTERFACE']</li>
    <li>$_SERVER['SERVER_ADDR']</li>
    <li>$_SERVER['SERVER_NAME']</li>
    <li>$_SERVER['SERVER_SOFTWARE']</li>
    <li>$_SERVER['SERVER_PROTOCOL']</li>
    <li>$_SERVER['REQUEST_METHOD']</li>
    <li>$_SERVER['REQUEST_TIME']</li>
    <li>$_SERVER['QUERY_STRING']</li>
    <li>$_SERVER['DOCUMENT_ROOT']</li>
    <li>$_SERVER['HTTP_ACCEPT']</li>
    <li>$_SERVER['HTTP_ACCEPT_CHARSET']</li>
    <li>$_SERVER['HTTP_ACCEPT_ENCODING']</li>
    <li>$_SERVER['HTTP_ACCEPT_LANGUAGE']</li>
    <li>$_SERVER['HTTP_CONNECTION']</li>
    <li>$_SERVER['HTTP_HOST']</li>
    <li>$_SERVER['HTTP_REFERER']</li>
    <li>$_SERVER['HTTP_USER_AGENT']</li>
    <li>$_SERVER['HTTPS']</li>
    <li>$_SERVER['REMOTE_ADDR']</li>
    <li>$_SERVER['REMOTE_HOST']</li>
    <li>$_SERVER['REMOTE_PORT']</li>
    <li>$_SERVER['SCRIPT_FILENAME']</li>
    <li>$_SERVER['SERVER_ADMIN']</li>
    <li>$_SERVER['SERVER_PORT']</li>
    <li>$_SERVER['SERVER_SIGNATURE']</li>
    <li>$_SERVER['PATH_TRANSLATED']</li>
    <li>$_SERVER['SCRIPT_NAME']</li>
    <li>$_SERVER['REQUEST_URI']</li>
    <li>$_SERVER['PHP_AUTH_DIGEST']</li>
    <li>$_SERVER['PHP_AUTH_USER']</li>
    <li>$_SERVER['PHP_AUTH_PW']</li>
    <li>$_SERVER['AUTH_TYPE']</li>
    </ul>
	

</div>



</div>

<?php require_once __DIR__ . "/../inc/footer.php"; ?>